# Stack FRONTEND — Portainer (misma red que backend y Postgres).
# BACKEND_HOST = servicio del API en el otro stack (backend-api).
version: "3.9"

services:
  frontend-web:
    image: alek21/brandonpesantez-reciclaje-frontend:v4
    container_name: frontend-app
    restart: always
    ports:
      - "8080:80"
    networks:
      - red_reciclaje

networks:
  red_reciclaje:
    external: true
